# Generated by Django 5.0.1 on 2024-01-30 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='conform_password',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=6)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
